{% set name = "conda-bash-completion" %}
{% set version = "1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tartansandal/{{ name }}/archive/{{ version }}.tar.gz
  sha256: fc2c3d0181c0e3303387a575cb06ebe81cdecbcf311bba6f476588afc86216c4

build:
  number: 1
  skip: true  # [win]

requirements:
  run:
    - bash-completion

test:
  source_files:
    - conda

  requires:
    - bash >=4.1

about:
  home: https://github.com/tartansandal/conda-bash-completion
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Bash completion for the conda commmand.

extra:
  recipe-maintainers:
    - tartansandal
