{% set name = "conda-bash-completion" %}
{% set version = "1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tartansandal/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 49d3be82eeb4a3e96cbc40f268988ad24d6367650e078f152149a3e2eb886039

build:
  number: 0
  skip: true  # [win]

requirements:
  run:
    - bash-completion

test:
  source_files:
    - conda

  requires:
    - bash >=4.1

about:
  home: https://github.com/tartansandal/conda-bash-completion
  license: GPL3
  license_file: LICENSE
  summary: Bash completion for the conda commmand.

extra:
  recipe-maintainers:
    - tartansandal
